alpha_exchange/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
    path('users/', include('users.urls')),
    path('about/', include('about.urls')),
    path('contact/', include('contact.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
"""
A Module to hold all the URL's for the home app.
"""
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home')
]

products/urls.py
"""
A Module to hold all the URL's for the products app.
"""
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ListProducts.as_view(), name='all_products'),
    path('search/', views.SearchProduct.as_view(), name='search_products'),
    path('<product_id>', views.ProductDetail.as_view(), name='product_detail'),
    path('categories/', views.categories, name="categories"),
    path('categories_list/<str:cats>', views.categories_view,
         name="categories_list"),
    path(
        'create_product/', views.ProductCreate.as_view(),
        name='create_product'),
    path(
        'update/<str:pk>/', views.ProductUpdate.as_view(),
        name='update_product'),
    path(
        'delete/<str:pk>/', views.ProductDelete.as_view(),
        name='delete_product'),
    path(
        'create_category/', views.CategoryCreate.as_view(),
        name='create_category'
        ),
    path(
        '<int:pk>/update_category/', views.CategoryUpdate.as_view(),
        name='update_category'
        ),
    path(
        '<int:pk>/delete_category/', views.CategoryDelete.as_view(),
        name='delete_category'
        ),
    path(
        'like/<product_id>/', views.ProductLike.as_view(),
        name='product_like'),
    path(
        'edit_review/<int:pk>', views.EditReview.as_view(),
        name="edit_review"),
    path(
        'delete_review/<int:review_id>', views.delete_review,
        name="delete_review"),
]

checkout/models.py
"""
A module containing models for the checkout app.
"""
import uuid
from django.db import models
from django.db.models import Sum
from django.conf import settings
from django_countries.fields import CountryField
from products.models import Product
from users.models import UserAccount


class Order(models.Model):
    """
    A class for creating a order on the website.
    """

    # UserAccount foreign key
    user_account = models.ForeignKey(UserAccount, on_delete=models.SET_NULL,
                                     null=True, blank=True,
                                     related_name='orders')

    # Name and address information
    full_name = models.CharField(max_length=50, null=False, blank=False)
    street_address1 = models.CharField(max_length=80, null=False, blank=False)
    street_address2 = models.CharField(max_length=80, null=True, blank=True)
    town_or_city = models.CharField(max_length=40, null=False, blank=False)
    county = models.CharField(max_length=80, null=True, blank=True)
    country = CountryField(blank_label='Country *', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    email = models.EmailField(max_length=254, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)

    # Order number and details
    order_number = models.CharField(max_length=32, null=False, editable=False)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    original_basket = models.TextField(null=False, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=254, null=False, blank=False, default='')

    def _gen_order_num(self):
        """
        Generate a unique order number using UUID, for each order.
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update grand_total when a new item is added to the order, inc delivery.
        """
        self.order_total = self.lineitems.aggregate(
            Sum('lineitem_total'))['lineitem_total__sum'] or 0
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            sdp = settings.STANDARD_DELIVERY_PERCENTAGE
            self.delivery_cost = self.order_total * sdp / 100
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the default save method to check for an
        order number if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._gen_order_num()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    """
    A class for calculating the individual items on an order.
    """

    order = models.ForeignKey(
        Order, null=False, blank=False, on_delete=models.CASCADE,
        related_name='lineitems')
    product = models.ForeignKey(
        Product, null=False, blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(max_length=2, null=True, blank=True)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, blank=False,
        editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method calculate the
        lineitem total and update the order.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'SKU {self.product.sku} on order {self.order.order_number}'

products/views.py
"""
A module containing the views within the products app.
"""
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import (
    render, redirect, reverse, get_object_or_404, HttpResponseRedirect)
from django.views.generic import (
    ListView, CreateView, UpdateView, DeleteView, View)
from users.models import UserAccount
from .product_filters import ProductFilter, ProductOrderFilter
from .models import Product, Category, Review
from .forms import ProductModelForm, CategoryModelForm, ReviewForm


class ListProducts(ListView):
    """
    A class to view all the products with filtering and sorting.
    """
    model = Product
    paginate_by = 12

    def __init__(self):
        self.no_search_result = True

    def get_queryset(self, **kwargs):
        search_results = ProductFilter(self.request.GET, self.queryset)
        if search_results.qs:
            self.no_search_result = False
        # Returns the default queryset if an empty
        # queryset is returned by the django_filters
        return search_results.qs.distinct() or self.model.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['filter'] = ProductFilter(
            self.request.GET, queryset=self.get_queryset()
            )
        return context


class SearchProduct(ListView):
    """
    A class to view the search results with filtering and sorting.
    """
    model = Product
    paginate_by = 12

    def __init__(self):
        self.no_search_result = True

    def get_queryset(self, **kwargs):
        search_results = ProductOrderFilter(self.request.GET, self.queryset)
        queryset = search_results.qs.distinct()
        # get search criteria
        query = self.request.GET.get('q')
        if not query:
            # send error message if nothing entered
            messages.error(
                self.request, 'You did not enter any search criteria'
                )
            return Product.objects.none()
        if query:
            # apply filters to all products
            search_results = queryset.filter(
                Q(name__icontains=query) |
                Q(description__icontains=query) |
                Q(recommended_use__icontains=query)).distinct()
        if search_results:
            self.no_search_result = False
        # Returns the queryset returned by the django_filters
        return search_results

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['filter'] = ProductOrderFilter(
            self.request.GET, queryset=Product.objects.all()
            )
        return context


class ProductDetail(View):
    """
    Displays the product details page by product ID.
    """

    def get(self, request, product_id):
        """
        fetches the information on the product, reviews and likes.
        """
        queryset = Product.objects.all()
        product = get_object_or_404(queryset, pk=product_id)
        reviews = product.review.filter(approved=True).order_by("timestamp")
        number_of_reviews = reviews.count
        liked = False
        if request.user.is_authenticated:
            profile = get_object_or_404(UserAccount, user=request.user)
            if product.likes.filter(id=profile.id).exists():
                liked = True

        context = {
            'product': product,
            "reviews": reviews,
            "review_posted": False,
            "liked": liked,
            "review_form": ReviewForm(),
            'number_reviews': number_of_reviews,
        }

        return render(request, 'products/product_detail.html', context)

    def post(self, request, product_id):
        """
        Handles the review form post
        """
        queryset = Product.objects.all()
        product = get_object_or_404(queryset, pk=product_id)
        reviews = product.review.filter(approved=True).order_by("timestamp")
        liked = False
        if request.user.is_authenticated:
            profile = get_object_or_404(UserAccount, user=request.user)
            if product.likes.filter(id=profile.id).exists():
                liked = True

        review_form = ReviewForm(data=request.POST)
        if review_form.is_valid():
            review_form.instance.author = profile
            review = review_form.save(commit=False)
            review.product = product
            review.save()
            messages.success(
                request, "Your review was has been posted successfully.")
        else:
            review_form = ReviewForm()
            messages.success(
                request,
                "Your review was not submitted, please check the form.")

        context = {
                "product": product,
                "reviews": reviews,
                "review_posted": True,
                "review_form": review_form,
                "liked": liked,
            }

        return render(
            request, 'products/product_detail.html', context)


class EditReview(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    """
     Allow users to edit their reviews.
    """
    queryset = Review.objects.all()
    template_name = 'products/edit_review.html'
    form_class = ReviewForm
    success_message = 'The review was successfully updated'


@login_required
def delete_review(request, review_id):
    """
    Delete user Reviews from the website
    """
    review = get_object_or_404(Review, pk=review_id)
    review.delete()
    messages.success(request, 'The review was deleted successfully')
    return HttpResponseRedirect(reverse(
        'product_detail', args=[review.product.id]))


class ProductLike(View):
    """
    Adds or removes the like from a product
    """
    def post(self, request, product_id, *args, **kwargs):
        queryset = Product.objects.all()
        product = get_object_or_404(queryset, pk=product_id)
        profile = get_object_or_404(UserAccount, user=request.user)
        if product.likes.filter(id=profile.id).exists():
            product.likes.remove(profile)
        else:
            product.likes.add(profile)

        return HttpResponseRedirect(
            reverse('product_detail', args=[product_id]))


def categories(request):
    """
    Renders the categories page.
    """
    return render(request, 'products/categories.html')


def categories_view(request, cats):
    """
    Renders the products filtered by categories.
    """
    context = {}

    filtered_products = ProductOrderFilter(
        request.GET, queryset=Product.objects.filter(
            category__friendly_name__contains=cats))

    context['filter'] = filtered_products

    paginated_filtered_products = Paginator(filtered_products.qs, 12)

    page_number = request.GET.get('page')
    page_obj = paginated_filtered_products.get_page(page_number)

    context['cats'] = cats
    context['page_obj'] = page_obj

    return render(request, 'products/category.html', context)


class ProductCreate(UserPassesTestMixin, CreateView):
    """
    A class view to create products
    """
    template_name = 'products/create_product.html'
    form_class = ProductModelForm
    queryset = Product.objects.all()

    def test_func(self):
        # check if user is a superuser
        return self.request.user.is_superuser

    def form_valid(self, form):
        # if form was valid send success message
        messages.success(self.request, 'Product created successfully.')
        return super().form_valid(form)

    def form_invalid(self, form):
        context = self.get_context_data(form=form)
        # if form was invalid send error message
        context.update({"Error": "Something went wrong"})
        messages.error(
            self.request,
            "Sorry, something went wrong, please check the form again.")
        return self.render_to_response(context)

    def handle_no_permission(self):
        # if user not allowed redirect and send message
        messages.error(
            self.request,
            "You do not have permission to view this page.")
        return redirect('/accounts/login')


class ProductUpdate(UserPassesTestMixin, UpdateView):
    """
    A class view to update products
    """
    template_name = 'products/create_product.html'
    form_class = ProductModelForm
    queryset = Product.objects.all()

    def test_func(self):
        # check if user is a superuser
        return self.request.user.is_superuser

    def get_object(self, queryset=queryset):
        pk_ = self.kwargs.get("pk")
        return get_object_or_404(Product, pk=pk_)

    def form_valid(self, form):
        # if form was valid send success message and redirect to product
        messages.success(self.request, "Product updated successfully.")
        super().form_valid(form)
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        """
        If the form is invalid, render the invalid form.
        """
        # if form was invalid send error message
        messages.error(
            self.request,
            "Sorry there was an error, please check the form again.")
        return self.render_to_response(self.get_context_data(form=form))

    def handle_no_permission(self):
        # if user not allowed redirect and send message
        messages.error(
            self.request,
            "You do not have permission to view this page.")
        return redirect('/accounts/login')


class ProductDelete(UserPassesTestMixin, DeleteView):
    """
    A class view to delete products
    """

products/templates/products/delete_object.html
{% extends 'base.html' %}
{% load static %}
{% load tags %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'products/css/products.css' %}">
{% endblock %}

{% block extra_title %}{% if product %}Delete Product{% else %}Delete Category{% endif %}{% endblock %}

{% block content %}
<div class="container">
    <div class="col">
        <div class="row">
            <div class="col">
                <h1 class="my-5 text-center">
                    <!-- Title depends on the need -->
                    {% if product %}
                        Delete Product
                    {% else %}
                        Delete Category
                    {% endif %}
                </h1>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="row d-flex justify-content-center">
            <div class="col-12 col-lg-6 mb-5">
                <form action='.' method='POST'>
                    <!-- Confirmation of deletion form -->
                    {% csrf_token %}
                    <p>Are you sure you want to delete {{ object.name }}?</p>
                    <p>
                        <input class="btn btn-light" type='submit' value='Yes'>
                        <button class = "btn btn-light" href='{{request.META.HTTP_REFERER|escape}}'>Cancel</button>
                    </p>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'products/css/products.css' %}">
{% endblock %}

{% block extra_title %}{{ product.name }}{% endblock %}

{% block content %}
    <div class="container-fluid my-5">
        <div class="row justify-content-center">
            <div class="col-10">
                <div class="row">
                    <div class="col-md-6 d-flex justify-content-center justify-content-md-start">
                        <!-- Product image or default image -->
                        {% if product.image %}
                            <a href="{{ product.image.url }}" target="_blank">
                                <img class="cust-img p-0" width="600" height="800" src="{{ product.image.url }}" alt="{{ product.name }}">
                            </a>
                        {% else %}
                            <div class="d-flex text-center flex-fill">
                                <div class="d-flex align-self-center mx-auto">
                                    <p>AWAITING IMAGE</p>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-md-6">
                        <!-- Product information -->
                        <h1 class="display-6 mt-2">{{ product.name }}</h1>
                        <hr class="product-rule">
                        <p class=" my-0 mr-3">Price: £{{ product.price }}</p>
                        <p class=" my-0 mr-3">Recommended use: {{ product.recommended_use }}</p>
                        <p class=" my-0 mr-3">Product SKU: {{ product.sku.upper }}</p>
                        {% if product.rating %}
                            <p class="my-0 mr-3"><i class="fas fa-star mr-1"></i>Product Rating: {{ product.rating }} / 5</p>
                        {% else %}
                            <p class="my-0 mr-3">Product Rating: No Rating</p>
                        {% endif %}
                        {% if user.is_authenticated %}
                            <!-- Form to like/unlike a product -->
                            <form class="d-inline" action="{% url 'product_like' product.id %}" method="POST">
                                {% csrf_token %}
                                {% if liked %}
                                    <button class="btn btn-light" type="submit" value="{{ product.id }}">
                                        <span><i class="fas fa-heart"></i> Number of likes: {{ product.number_of_likes }}</span>
                                    </button>
                                {% else %}
                                    <button class="btn btn-light" type="submit" value="{{ product.id }}">
                                        <span><i class="far fa-heart"></i> Number of likes: {{ product.number_of_likes }}</span>
                                    </button>
                                {% endif %}
                            </form>
                        {% else %}
                            <!-- Lists number of likes -->
                            <span><i class="far fa-heart"></i>{{ product.number_of_likes }}</span>
                        {% endif %}
                        {% if product.category %}
                            <p class="my-0 mr-3">
                                <a class="btn btn-large btn-light mt-2" href="{% url 'all_products' %}?category={{ product.category.name }}">
                                    <i class="fas fa-tag mr-1"></i> {{ product.category.friendly_name }}
                                </a>
                            </p>
                        {% endif %}
                        <hr class="product-rule">
                        <form class="form" action="{% url 'add_to_basket' product.id %}" method="POST">
                            {% csrf_token %}
                            <div class="form-row">
                                {% with product.has_sizes as size %}
                                    {% if size %}
                                        <!-- Size selector box -->
                                        <div class="col-12">
                                            <p class="mb-0"><strong>Size:</strong></p>
                                            <div class="form-group w-50 my-2">
                                                <div class="input-group">
                                                    <select class="form-control select_input" id='id_product_size' aria-label="product_size" name="product_size">
                                                        <option value="xs">XS</option>
                                                        <option value="s">S</option>
                                                        <option value="m" selected>M</option>
                                                        <option value="l">L</option>
                                                        <option value="xl">XL</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                        <div class="col-12">
                                            <!-- Quantity input and buttons -->
                                            <p class="mb-0"><strong>Quantity:</strong></p>
                                            <div class="form-group w-50 my-2">
                                                <div class="input-group input-group-{{ item.item_id }}">
                                                    <button class="decrement-qty btn btn-light select_input rounded-start p-0 
                                                        decrement-qty_{{ product.id }}" data-item_id="{{ product.id }}">
                                                        <span class="sr-only">decrement-qty</span>
                                                        <i class="fas fa-minus"></i>
                                                    </button>
                                                    <label class="sr-only" for="id_qty_{{ product.id }}">quantity</label>
                                                    <input class="form-control select_input id_qty_{{ product.id }}" type="number"
                                                        name="quantity" value="1" min="1" max="99" data-item_id="{{ product.id }}" id="id_qty_{{ product.id }}">
                                                    <button class="increment-qty btn btn-light select_input rounded-end p-0
                                                        increment-qty_{{ product.id }}" data-item_id="{{ product.id }}">
                                                        <span class="sr-only">increment-qty</span>
                                                        <i class="fas fa-plus"></i>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                        <!-- Back to shop and add to basket buttons -->
                                        <div class="col-12">
                                            <a href="javascript:history.back()" class="btn btn-light mb-2">
                                                <i class="fas fa-arrow-left fa-lg"></i>
                                                <span>Back to the shop!</span>
                                            </a>
                                            <div class="d-flex m-0">
                                                <p class="input-wrapper btn-light m-0">
                                                    <label for="add_to_basket" class="fas fa-shopping-bag fa-lg basket-icon d-none">add to basket</label>
                                                    <input type="submit" id="add_to_basket" class="btn btn-light prod_details_btn" value="Add to Basket">
                                                </p>
                                            </div>
                                        </div>
                                    <input type="hidden" name="redirect_url" value="{{ request.path }}">
                                    {% endwith %}
                                </div>
                            </form>
                            <hr class="product-rule">
                            <div>
                                <!-- Product description -->
                                <h2> Product Description</h2>
                                <p class=" my-0 mr-3">{{ product.description }}</p>
                            </div>
                            {% include "products/includes/admin_buttons.html" %}
                        </div>
                    </div>
                    <div class="row-12">
                        <!-- Reviews form -->
                        <div class="post-reviews">
                            <div class="review-form">
                                <hr class="product-rule">
                                <!-- User taken crispy form for textbox -->
                                {% if user.is_authenticated %}
                                    <h3>Leave a review</h3>
                                    <p>Posting as: {{ user.username | slice:":10"}}</p>
                                    <form method="post">
                                        {% csrf_token %}
                                        {{ review_form | crispy }}
                                        <button type="submit" class="btn btn-light mt-3 mb-3">Submit</button>
                                    </form>
                                {% endif %}
                            </div>
                            <!-- Number of reviews -->
                            {% if reviews %}
                                <h4>Reviews: <span class="reviews"><i class="far fa-comments comments"></i>{{ number_reviews }}</span></h4>
                            {% else %}
                                <h4>No reviews yet: <span class="reviews"><i class="far fa-comments comments"></i>{{ number_reviews }}</span></h4>
                            {% endif %}
                            <!-- list of reviews -->
                            {% for review in reviews %}
                            <!-- Review title -->
                            <h3>{{ review.title }}</h3>
                            <div class="product-reviews">
                                <!-- Review author -->
                                <span>{{ review.author | slice:":10"}} | </span>
                                <!-- Review timestamp -->
                                <span><i class="fas fa-clock"></i> {{ review.timestamp|date:"d/m/Y H:i" }}</span>
                                <!-- Review content -->
                                <div class="product-reviews">
                                    <p class="m-0"></p>
                                    <div class="w-75"><i class="far fa-comment-dots"></i>{{ review.message | linebreaks }}</div>
                                </div>
                            </div>
                            <!-- Check if user is the same as author or is superuser -->
                            {% if user.is_authenticated and user.username == review.author or user.is_superuser %}
                            <!-- Edit review button -->
                            <a href="{% url 'edit_review' review.id %}" class="btn btn-light mb-3" aria-label="Go to the Edit Reviews Page">Edit</a>
                            <!-- Delete review button, opens modal -->
                            <button type="button" class="btn btn-light mb-3" data-bs-toggle="modal" data-bs-target="#delete-review">Delete</button>
                            <!-- Delete review bootstrap modal-->
                            <div class="modal fade" id="delete-review" tabindex="-1" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="staticBackdropLabel">Delete Review</h5>
                                        </div>
                                        <div class="modal-body">
                                            Are you sure you want to delete your review?
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn" data-bs-dismiss="modal">Close</button>
                                            <a href="{% url 'delete_review' review.id %}" class="btn btn-danger" aria-label="Delete Review">Delete</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                            <hr class="product-rule">
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div> 
        </div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script src="{% static 'products/js/qty-box.js' %}"></script>
{% endblock %}